server:
  port: 8080

manInfo:
    ip: 192.168.3.40
    sendip: http://192.168.3.4:8081
    port: 8080
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15
    url: jdbc:mysql://192.168.2.151:3306/
mybatis:
  mapper-locations: classpath:mapper/*.xml
email:
  mailSmtpHost: smtp.163.com
  mailSmtpPort: 25
  fromUserName: m17301071346@163.com
  fromUserPassword: xsc1007
  toEmail: songcui.xue@hoomsun.com

    
  