server:
  port: 8081

manInfo:
    ip: 192.168.3.11
    sendip: http://117.34.70.217:8080
    port: 8081
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15
    url: jdbc:mysql://192.168.2.151:3306/
mybatis:
  mapper-locations: classpath:mapper/*.xml

    
  